### ISSUE TITLE
Outline the asyncy.yml

### ISSUE THREAD

**Issue by stevepeak** [asyncy/docker-template#2]
A yaml file will container details on how the container will operate. This file needs to be outlined.

e.g., 

```yml
# if the container needs access to the
# story's shared volume
volume: false

# Details on this container to help users
help: |
  Service summary details

# outline the commands this service can do
commands:
  # define a custom command which
  # is called in the Storyscript as
  #     `res = container foobar`
  foobar:
    help: |
      Description of command
    args: 
      - name: ""
        type: string
        required: true
        help: |
          Description of this argument.

    # if the command accepts additional arguments
    # you can define what the types are
    # default is true
    additional_args: true
    # if the command accepts keyword arguments
    # default is true
    additional_kwargs: true

    # if the commnad will stream output
    streaming: false

    # declare what type of object
    # is the expected result
    result:
      type: json

    # if the command requires http
    # connections they can be defined as follows
    # port that service needs to bind to
    port: 5000

entrypoint:
  # same structure as above but used when no command is provided
  ...

# if the serice needs to prepare any assets
# this command is called at any point before the container
startup: "custom_script.sh"

# list the runtime privileges and linux capacities required
# to run this container. default is no capacities
# https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
cap:
- CHOWN

# define the environment variables this service may need
env:
  # This is the environment variable that is provided to docker
  # e.g., `docker run -e foo=bar`
  foo:
    # regexp configuration check
    pattern: null
    # if the environment is required to be set by the user
    requred: false
    # what the default value is, if not defined by the user
    default: null
    help: |
      Details on what the value should be and where to get it.

```

## Startup
Containers may require a script to run before upon startup. When the container is first created it will call the `startup` command. This is outside the scope of Storyscript execution. 

An example of this is connecting to a database and keeping that connection open so when the container is used it can execute the query quicker by having a live connection.
Another example is a container that needs to prefetch or render documents before being used.

Ports and volume will be provided to the container.

**Comment by Vesuvium** [comment]
- help: asyncy could use this as description in Emporium
- env: should define a subset of the vars allowed in the story repo?

Asyncy will need to know if the container has streaming capabilities.  Defining yields is optional, will be used for linting when writing stories.
```
streaming:
    type: http # http, websocket, rpc
    yields:
        - name: request
        - object:
            - write: method
```
